apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
spec:
  selector:
    app: laravel-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30000

